name: msl_oauth_login
description: Azure Active Directory OAuth2 authentication package for Flutter with a ready-to-use login button.
version: 1.0.0

environment:
  sdk: ^3.12.2
  flutter: '>=3.12.2'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  webview_flutter: ^4.4.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0
